import { Poppins } from "next/font/google";
import "./StyleCss/globals.css";

import Header from "./Components/UIUX/Header"
import Footer from "./Components/UIUX/Footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
});
const Mont = {
  variable: "--font-mont-heavy",
  className: "font-heading",
};
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  //   <html lang="en" className={poppins.variable}>
  //   <body className="antialiased">{children}</body>
  // </html>
  <html lang="en" className={`${poppins.variable} ${Mont.variable}`}>
  <body className="antialiased">
    <Header/>
    {children}
    <Footer/>
    </body>
</html>
  );
}
